name: apk_info_example
description: "Demonstrates how to use the apk_info plugin."
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  apk_info:
    path: ../
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true